### ISSUE TITLE
Fatal Error LogglyHandler::write()

### ISSUE THREAD

**Issue by pbruijnes** [FoxxMD/laravel-loggly#1]
Hi, I got this fatal-error while trying to implement your Service:
PHP Fatal error:  Call to protected method Monolog\Handler\LogglyHandler::write() from context 'App\Providers\LoggyServiceProvider' in [root]/app/Providers/LoggyServiceProvider.php

Solved it by removing the invocation of the monolog- write method and adding a Log pushhandler according to this url: http://chris.schalenborgh.be/2014/10/02/pushing-laravel-logs-loggly/

The boot method in LoggyServiceProvider looks like this now:

```
public function boot() {
        $app = $this->app;
        // Listen to log messages.
        $app['log']->listen(function () use ($app) {
            $logger = \Log::getMonolog();
            $logger->pushHandler($app['loggly.handler']);
        });
} 
```

**Comment by FoxxMD** [comment]
Awesome! I'm not actually using loggly anymore so I'm glad you could find a solution for this :) 

If you want to make a PR I will merge it! Otherwise I can make the change myself.
